services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ProductFeed\ZboziBundle\:
        resource: '../../*'

    Shopsys\ProductFeed\ZboziBundle\DataFixtures\:
        resource: '../../DataFixtures/*'
        tags:
            - { name: shopsys.data_fixture }

    Shopsys\ProductFeed\ZboziBundle\ZboziFeed:
        tags:
            - { name: shopsys.feed, hours: '3', minutes: '0' }

    Shopsys\ProductFeed\ZboziBundle\Form\ZboziProductCrudExtension:
        tags:
            - { name: shopsys.crud_extension, type: product }

    Shopsys\ProductFeed\ZboziBundle\Model\Product\ZboziProductDomainDataFactoryInterface:
        alias: Shopsys\ProductFeed\ZboziBundle\Model\Product\ZboziProductDomainDataFactory
