services:
  shopsys.product_feed.zbozi_bundle.feed_config:
    class: Shopsys\ProductFeed\ZboziBundle\ZboziFeedConfig
    tags:
      - { name: shopsys.product_feed }

  shopsys.product_feed.zbozi_bundle.product_crud_extension:
    class: Shopsys\ProductFeed\ZboziBundle\ZboziProductCrudExtension
    tags:
      - { name: shopsys.crud_extension, type: product }

  shopsys.product_feed.zbozi_bundle.product_form_type:
    class: Shopsys\ProductFeed\ZboziBundle\ZboziProductFormType
    tags:
      - { name: form.type }

  shopsys.product_feed.zbozi_bundle.data_fixture:
    class: Shopsys\ProductFeed\ZboziBundle\ZboziPluginDataFixture
    tags:
      - { name: shopsys.data_fixture}
